name: branch-build

on:
  push:
    branches:
      - 'main'
      - 'test'

env:
  DOCKERHUB_USERNAME: z43811702

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Get commit hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Current commit hash is: $COMMIT_HASH"
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
      - 
        name: Get branch name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Current branch is: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/github-action-demo:${{ env.COMMIT_HASH }}
            ${{ env.DOCKERHUB_USERNAME }}/github-action-demo:${{ env.BRANCH_NAME }}