name: branch-build

on:
  push:
    tags:
      - 'v*'

env:
  DOCKERHUB_USERNAME: z43811702

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Get tag name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # 去掉前缀 'v'，如果标签名以 'v' 开头
          if [[ "$TAG_NAME" == v* ]]; then
            TAG_NAME="${TAG_NAME:1}"
          fi

          echo "Tag name without 'v': $TAG_NAME"

          echo "IMAGE_TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/github-action-demo:${{ env.IMAGE_TAG_NAME }}