name: branch-build

on:
  push:
    tags:
      - 'v*'

env:
  DOCKERHUB_USERNAME: z43811702

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Get commit hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Current commit hash is: $COMMIT_HASH"
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
      - 
        name: Get tag name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # 去掉前缀 'v'，如果标签名以 'v' 开头
          if [[ "$TAG_NAME" == v* ]]; then
            TAG_NAME="${TAG_NAME:1}"
          fi

          echo "Tag name without 'v': $TAG_NAME"

          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Pull existing image
        run: |
          docker pull ${{ env.DOCKERHUB_USERNAME }}/github-action-demo:${{ env.COMMIT_HASH }}
      - 
        name: Retag and push image
        run: |
          docker tag ${{ env.DOCKERHUB_USERNAME }}/github-action-demo:${{ env.COMMIT_HASH }} ${{ env.DOCKERHUB_USERNAME }}/github-action-demo:${{ env.TAG_NAME }}
          docker push ${{ env.DOCKERHUB_USERNAME }}/github-action-demo:${{ env.TAG_NAME }}